# Build PDF on GitHub
name: LaTeX CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: false
      - uses: actions/upload-artifact@v4
        with:
          name: 3dof-report-pdf
          path: main.pdf
